service: trader-data-processing

frameworkVersion: "3"

provider:
  name: aws
  region: us-east-2
  runtime: python3.10
  deploymentBucket:
    name: ${param:deployment-bucket}
    serverSideEncryption: AES256
  timeout: 60
  environment:
    REGION: ${self:provider.region}
    DEPLOY_ENV: ${opt:stage}
    DATA_COLLECTION_BUCKET_NAME: ${self:custom.data_collection_bucket_name}
    CONTAINER_IMAGE_URI: ${self:custom.container_image_uri}
    MEMORY: ${self:custom.memory}
    CPU: ${self:custom.cpu}
    CONTAINER_PORT: ${self:custom.container_port}
    HOST_PORT: ${self:custom.host_port}
    EXECUTION_ROLE_ARN: ${self:custom.env.service_role}
    TASK_ROLE_ARN: ${self:custom.env.job_flow_role_name}
    CLUSTER: ${self:custom.cluster}
    RELEASE_LABEL: ${self:custom.env.release_label}
    IDLE_TIMEOUT: ${self:custom.env.idle_timeout}
    SERVICE_NAME: ${self:custom.service}
    COINBASE_API_KEY: ${self:custom.coinbase_api_key}
    COINBASE_API_SECRET: ${self:custom.coinbase_api_secret}
    AUTH0_ASSISTANT_AUDIENCE: ${self:custom.auth0_assistant_audience}
    ASSISTANT_API_KEY: ${self:custom.assistant_api_key}
    AUTH0_ASSISTANT_CLIENT_ID: ${self:custom.auth0_assistant_client_id}
    AUTH0_ASSISTANT_CLIENT_SECRET: ${self:custom.auth0_assistant_client_secret}
    AUTH0_OAUTH_URL: ${self:custom.env.auth0_oauth_url}
    CACHE_TABLE_NAME: ${self:custom.cache_table_name}
  tags:
    app_name: ${self:service}-${opt:stage}

custom:
  stage: ${opt:stage}
  region: ${opt:region}
  env: ${file(slsenvs.yml):${self:custom.stage}}
  container_name: ${param:container_name, '${self:service}-container-${self:custom.stage}-${self:custom.region}'}
  memory: ${param:memory, 512}
  cpu: ${param:cpu, 256}
  container_port: ${param:container_port, 80}
  host_port: ${param:host_port, 80}
  execution_role_arn: ${param:execution_role_arn, 'arn:aws:iam::${aws.accountId}:role/${self:service}-task-execution-role-blue-${self:custom.stage}-${self:custom.region}'}
  task_role_arn: ${param:task_role_arn, 'arn:aws:iam::${aws.accountId}:role/${self:service}-task-role-blue-${self:custom.stage}-${self:custom.region}'}
  cluster: ${param:cluster, '${self:service}-cluster-${self:custom.stage}-${self:custom.region}'}
  master_instance_type: ${param:master_instance_type, 'm5.xlarge'}
  master_instance_count: ${param:master_instance_count, 1}
  core_instance_type: ${param:core_instance_type, 'm5.xlarge'}
  core_instance_count: ${param:core_instance_count, 2}
  subnet_id: ${param:subnet_id, '${self:custom.env.subnet_id}'}
  ec2_key_pair: ${param:ec2_key_pair, '${self:custom.env.ec2_key_pair}'}
  job_flow_role_name: ${param:job_flow_role_name, '${self:service}-instance-profile-blue-${self:custom.stage}-${self:custom.region}'}
  service_role: ${param:service_role, '${self:service}-service-role-blue-${self:custom.stage}-${self:custom.region}'}
  idle_timeout: ${param:idle_timeout, 3600}
  spark_job_name: ${param:spark_job_name, '${self:service}-job-${self:custom.stage}-${self:custom.region}'}
  service: ${param:service, '${self:service}-service-${self:custom.stage}-${self:custom.region}'}
  coinbase_api_key: ${param:coinbase_api_key, '${self:custom.env.coinbase_api_key}'}
  coinbase_api_secret: ${param:coinbase_api_secret, '${self:custom.env.coinbase_api_secret}'}
  auth0_assistant_client_id: ${param:auth0_assistant_client_id, '${self:custom.env.auth0_assistant_client_id}'}
  auth0_assistant_client_secret: ${param:auth0_assistant_client_secret, '${self:custom.env.auth0_assistant_client_secret}'}
  auth0_assistant_audience: ${param:auth0_assistant_audience, '${self:custom.env.auth0_assistant_audience}'}
  auth0_oauth_url: ${param:auth0_oauth_url, '${self:custom.env.auth0_oauth_url}'}
  assistant_api_key: ${param:assistant_api_key, '${self:custom.env.assistant_api_key}'}
  cache_table_name: ${param:cache_table_name, '${self:custom.env.cache_table_name}'}
  data_collection_bucket_name: ${param:data_collection_bucket_name, '${self:custom.env.data_collection_bucket_name}'}
  logRetentionInDays: 7
  pythonRequirements:
    dockerizePip: true
    slim: true
    layer:
      compatibleRuntimes:
        - python3.10

functions:
  ecs_task_handler:
    handler: consumer.ecs_orchestrate.sqs_record_handler
    role: arn:aws:iam::${aws.accountId}:role/${self:service}-role-blue-${self:custom.stage}-${self:custom.region}
    timeout: 30
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TaskQueue
              - Arn

resources:
  Resources:
    DataTrainCluster:
      Type: AWS::ECS::Cluster
      Properties:
        ClusterName: ${self:service}-cluster-${self:custom.stage}
        Tags:
          - Key: app_name
            Value: ${self:provider.tags.app_name}
    DataTrainService:
      Type: AWS::ECS::Service
      Properties:
        Cluster: ${self:service}-cluster-${self:custom.stage}
        DesiredCount: 0
        LaunchType: FARGATE
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED
            SecurityGroups:
              - ${param:security-group-id}
            Subnets:
              - ${param:subnet-id}
        TaskDefinition: !Ref DataTrainTaskDefinition
        Tags:
          - Key: app_name
            Value: ${self:provider.tags.app_name}
    # DataTrainTaskDefinition:
    #   Type: "AWS::ECS::TaskDefinition"
    #   Properties:
    #     Family: "${self:service}-task-family"
    #     ContainerDefinitions:
    #       - Name: ${self:service}-container
    #         Image: ${param:container-image}
    #         Memory: 512
    #         Cpu: 256
    #         Essential: true
    #         PortMappings:
    #           - ContainerPort: 80
    #             HostPort: 80
    #     NetworkMode: "awsvpc"
    #     RequiresCompatibilities:
    #       - "FARGATE"
    #     Cpu: "256"
    #     Memory: "512"
    #     ExecutionRoleArn: arn:aws:iam::${aws:accountId}:role/${self:service}-task-execution-role-blue-${self:custom.stage}-${self:custom.region}
    #     TaskRoleArn: arn:aws:iam::${aws:accountId}:role/${self:service}-task-handler-role-blue-${self:custom.stage}-${self:custom.region}
    #     Tags:
    #       - Key: app_name
    #         Value: ${self:provider.tags.app_name}
    DataTrainLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /ecs/${self:service}-${self:custom.stage}
        RetentionInDays: 7
        Tags:
          - Key: app_name
            Value: ${self:provider.tags.app_name}
    TaskQueue:
      Type: AWS::SQS::Queue
      Properties:
        FifoQueue: true
        QueueName: ${self:service}-task-queue-${self:custom.stage}.fifo
        MessageRetentionPeriod: 60
        VisibilityTimeout: 300
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt TaskDLQ.Arn
          maxReceiveCount: 1
        Tags:
            - Key: app_name
              Value: ${self:provider.tags.app_name}
    TaskDLQ:
      Type: AWS::SQS::Queue
      Properties:
        FifoQueue: true
        QueueName: ${self:service}-task-dlq-${self:custom.stage}.fifo
        Tags:
          - Key: app_name
            Value: ${self:provider.tags.app_name}

plugins:
  - serverless-deployment-bucket
  - serverless-plugin-log-retention
  - serverless-python-requirements
