name: "Deploy PROD Collection"

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Pick action
        options:
        - deploy
        - destroy
      region:
        type: choice
        description: Pick region
        options:
        - us-east-2

env:
  ENV: prod
  REGION: ${{ inputs.region }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
  AWS_DEFAULT_REGION: ${{ inputs.region }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Deploy
        run: |
          ./run ${{ inputs.action }}-service collection
