name: "Deploy/Destroy DEV LLM"

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Pick action
        options:
        - deploy
        - destroy
      region:
        type: string
        description: Specify region

env:
  ENV: dev
  REGION: ${{ inputs.region }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_LLM }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_LLM }}
  AWS_DEFAULT_REGION: ${{ inputs.region }}
  DEPLOYMENT_BUCKET: ${{ secrets.DEPLOYMENT_BUCKET }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Deploy
        run: |
          ./run ${{ inputs.action }}-service llm
