name: Unit Tests

on:
  workflow_call:
    inputs:
      marks:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      marks:
        type: string
        required: true
        default: 'unit-tests'
        description: 'Enter the marks'

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Run Collection Unit Tests
        run: |
          cd ./collection
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          ./run ${{ inputs.action }}-service collection || exit 1
          cd ..
      - name: Run LLM Unit Tests
        run: |
          cd ./llm
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          ./run ${{ inputs.action }}-service llm || exit 1
          cd ..
      - name: Run Processing Unit Tests
        run: |
          cd ./processing
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          ./run ${{ inputs.action }}-service processing || exit 1
          cd ..
